# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/garnet/Desktop/Programming/fractle/mandlebrot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/garnet/Desktop/Programming/fractle/mandlebrot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/garnet/Desktop/Programming/fractle/mandlebrot/CMakeFiles /home/garnet/Desktop/Programming/fractle/mandlebrot/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/garnet/Desktop/Programming/fractle/mandlebrot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named view

# Build rule for target.
view: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 view
.PHONY : view

# fast build rule for target.
view/fast:
	$(MAKE) -f CMakeFiles/view.dir/build.make CMakeFiles/view.dir/build
.PHONY : view/fast

#=============================================================================
# Target rules for targets named sim

# Build rule for target.
sim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sim
.PHONY : sim

# fast build rule for target.
sim/fast:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/build
.PHONY : sim/fast

#=============================================================================
# Target rules for targets named model

# Build rule for target.
model: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 model
.PHONY : model

# fast build rule for target.
model/fast:
	$(MAKE) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/build
.PHONY : model/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/model/genfrac.o: src/model/genfrac.cpp.o

.PHONY : src/model/genfrac.o

# target to build an object file
src/model/genfrac.cpp.o:
	$(MAKE) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/genfrac.cpp.o
.PHONY : src/model/genfrac.cpp.o

src/model/genfrac.i: src/model/genfrac.cpp.i

.PHONY : src/model/genfrac.i

# target to preprocess a source file
src/model/genfrac.cpp.i:
	$(MAKE) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/genfrac.cpp.i
.PHONY : src/model/genfrac.cpp.i

src/model/genfrac.s: src/model/genfrac.cpp.s

.PHONY : src/model/genfrac.s

# target to generate assembly for a file
src/model/genfrac.cpp.s:
	$(MAKE) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/genfrac.cpp.s
.PHONY : src/model/genfrac.cpp.s

src/view/gui.o: src/view/gui.cpp.o

.PHONY : src/view/gui.o

# target to build an object file
src/view/gui.cpp.o:
	$(MAKE) -f CMakeFiles/view.dir/build.make CMakeFiles/view.dir/src/view/gui.cpp.o
.PHONY : src/view/gui.cpp.o

src/view/gui.i: src/view/gui.cpp.i

.PHONY : src/view/gui.i

# target to preprocess a source file
src/view/gui.cpp.i:
	$(MAKE) -f CMakeFiles/view.dir/build.make CMakeFiles/view.dir/src/view/gui.cpp.i
.PHONY : src/view/gui.cpp.i

src/view/gui.s: src/view/gui.cpp.s

.PHONY : src/view/gui.s

# target to generate assembly for a file
src/view/gui.cpp.s:
	$(MAKE) -f CMakeFiles/view.dir/build.make CMakeFiles/view.dir/src/view/gui.cpp.s
.PHONY : src/view/gui.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... view"
	@echo "... sim"
	@echo "... model"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/model/genfrac.o"
	@echo "... src/model/genfrac.i"
	@echo "... src/model/genfrac.s"
	@echo "... src/view/gui.o"
	@echo "... src/view/gui.i"
	@echo "... src/view/gui.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

